SELECT * FROM Paciente

BEGIN TRANSACTION --TRAN
	UPDATE Paciente SET observacion='Estos son de la misma familia' WHERE apellido='Smail'
IF @@ROWCOUNT=1 --REGISTROS MODIFICADOS EN LA OPERACION ANTERIOR
	COMMIT TRAN --CONFIRMA TRANSACCION
ELSE
	ROLLBACK TRANSACTION --DECLINA TRANSACCION

SELECT * FROM Turno
BEGIN TRAN
	DELETE FROM Turno WHERE estado=1
IF @@ROWCOUNT=2
	COMMIT TRAN
ELSE
	ROLLBACK TRAN
