SELECT * FROM Paciente
SELECT * FROM TurnoPaciente

SELECT * FROM Paciente P
--INNER JOIN TurnoPaciente T --INTERSECCION DE LAS TABLAS
--LEFT JOIN TurnoPaciente T --PRIORIDAD LA PRIMER TABLA
RIGHT JOIN TurnoPaciente T --PRIORIDAD LA SEGUNDA TABLA
ON T.idPaciente=P.idPaciente --TIENEN QUE SER PK
--DEL LADO IZQUIERDO EL DATO DE LA SEGUNDA TABLA

--------------------
--UNIONS
--UNION ELIMINA REPETICIONES
--UNION ALL TRAE TODO INCLUSO REPETIDOS
SELECT * FROM Turno WHERE estado=0
UNION --LAS TABLAS DEBEN TENER LOS MISMOS CAMPOS!
SELECT * FROM Turno WHERE estado=2

SELECT idTurno FROM Turno WHERE estado=0
UNION ALL--LAS TABLAS DEBEN TENER LOS MISMOS CAMPOS!
SELECT idPaciente FROM Paciente